url: "https://stephencz.com"
permalink: /posts/:title

markdown: kramdown
kramdown:
  input: GFM
  highlighter: rouge
  parse_block_html: true
  syntax_highlighter_opts:
    block:
      line_numbers: true

sass:
  style: compressed

plugins:
  - jekyll-sitemap

exclude:
  - scripts
  - /screenshot.png
  - /README.md
  - /LICENSE