url: "https://stephencz.com"
permalink: /posts/:title

markdown: kramdown
kramdown:
  input: GFM
  highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

plugins:
  - jekyll-sitemap